export const PROMPT_ENHANCEMENT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "feature",
    "taskIntent",
    "sourceImageUnderstanding",
    "regionUnderstanding",
    "subjectPlan",
    "compositionPlan",
    "stylePlan",
    "textPlan",
    "additionalPromptUnderstanding",
    "scenePlan",
    "constraints",
    "negativeConstraints",
    "modelHints",
    "finalPrompt",
  ],
  properties: {
    feature: { type: "string" },
    taskIntent: { type: "string" },
    sourceImageUnderstanding: {
      type: "object",
      additionalProperties: false,
      required: [
        "mainSubject",
        "scene",
        "style",
        "colorPalette",
        "composition",
        "lighting",
        "materialTexture",
        "textAreas",
        "commercialUse",
      ],
      properties: {
        mainSubject: { type: "string" },
        scene: { type: "string" },
        style: { type: "string" },
        colorPalette: { type: "string" },
        composition: { type: "string" },
        lighting: { type: "string" },
        materialTexture: { type: "string" },
        textAreas: { type: "array", items: { type: "string" } },
        commercialUse: { type: "string" },
      },
    },
    regionUnderstanding: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["regionLabel", "targetObject", "operationBoundary", "notes"],
        properties: {
          regionLabel: { type: "string" },
          targetObject: { type: "string" },
          operationBoundary: { type: "string" },
          notes: { type: "string" },
        },
      },
    },
    subjectPlan: {
      type: "object",
      additionalProperties: false,
      required: ["keep", "remove", "replace", "generate"],
      properties: {
        keep: { type: "array", items: { type: "string" } },
        remove: { type: "array", items: { type: "string" } },
        replace: { type: "array", items: { type: "string" } },
        generate: { type: "array", items: { type: "string" } },
      },
    },
    compositionPlan: {
      type: "object",
      additionalProperties: false,
      required: ["layout", "cameraAngle", "visualHierarchy", "comparisonStructure"],
      properties: {
        layout: { type: "string" },
        cameraAngle: { type: "string" },
        visualHierarchy: { type: "string" },
        comparisonStructure: { type: "string" },
      },
    },
    stylePlan: {
      type: "object",
      additionalProperties: false,
      required: ["visualStyle", "colorScheme", "marketStyle"],
      properties: {
        visualStyle: { type: "string" },
        colorScheme: { type: "string" },
        marketStyle: { type: "string" },
      },
    },
    textPlan: {
      type: "object",
      additionalProperties: false,
      required: ["primaryText", "secondaryText", "textAccuracyRequirement", "avoidText"],
      properties: {
        primaryText: { type: "array", items: { type: "string" } },
        secondaryText: { type: "array", items: { type: "string" } },
        textAccuracyRequirement: { type: "string" },
        avoidText: { type: "array", items: { type: "string" } },
      },
    },
    additionalPromptUnderstanding: {
      type: "object",
      additionalProperties: false,
      required: ["acceptedRequirements", "conflictingRequirements", "mergedIntoFinalPrompt"],
      properties: {
        acceptedRequirements: { type: "array", items: { type: "string" } },
        conflictingRequirements: { type: "array", items: { type: "string" } },
        mergedIntoFinalPrompt: { type: "array", items: { type: "string" } },
      },
    },
    scenePlan: {
      type: "object",
      additionalProperties: false,
      required: ["sceneList", "sceneConstraints"],
      properties: {
        sceneList: { type: "array", items: { type: "string" } },
        sceneConstraints: { type: "string" },
      },
    },
    constraints: { type: "array", items: { type: "string" } },
    negativeConstraints: { type: "array", items: { type: "string" } },
    modelHints: {
      type: "object",
      additionalProperties: false,
      required: ["aspectRatio"],
      properties: {
        aspectRatio: { type: "string" },
      },
    },
    finalPrompt: { type: "string" },
  },
} as const;
