/** Shared UI class tokens aligned with docs/UI-DESIGN.md */

export const UI = {
  page: 'ui-page',
  pageScroll: 'ui-page-scroll',
  card: 'ui-card',
  cardPadded: 'ui-card-padded',
  pageTitle: 'ui-page-title',
  pageSubtitle: 'ui-page-subtitle',
  label: 'ui-label',
  labelMono: 'ui-label-mono',
  input: 'ui-input',
  inputCompact: 'ui-input-compact',
  textarea: 'ui-textarea',
  select: 'ui-select',
  btnPrimary: 'ui-btn-primary',
  btnSecondary: 'ui-btn-secondary',
  btnGhost: 'ui-btn-ghost',
  subtabBar: 'ui-subtab-bar',
  subtab: 'ui-subtab',
  subtabActive: 'ui-subtab-active',
  subtabIndicator: 'ui-subtab-indicator',
  paramPanel: 'ui-param-panel',
  previewPanel: 'ui-preview-panel',
  segmentActive: 'ui-segment-active',
  segmentInactive: 'ui-segment-inactive',
  alertSuccess: 'ui-alert-success',
  alertError: 'ui-alert-error',
  badgeSuccess: 'ui-badge-success',
  badgeWarning: 'ui-badge-warning',
  badgeInfo: 'ui-badge-info',
  badgeError: 'ui-badge-error',
  statCard: 'ui-stat-card',
  tableHeader: 'ui-table-header',
  tableRow: 'ui-table-row',
  uploadZone: 'ui-upload-zone',
  /** 图片/框选横向瓦片网格：一行最多 4 张 */
  uploadTileGrid: 'grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4',
  modalOverlay: 'ui-modal-overlay',
  modal: 'ui-modal',
} as const;
